# Generated by Django 2.2.4 on 2019-09-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_cascade_delete_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='token'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='kind',
            field=models.CharField(choices=[('register', 'Registration'), ('auth', 'Authorization'), ('refund', 'Refund'), ('capture', 'Capture'), ('void', 'Void')], max_length=10, verbose_name='kind'),
        ),
    ]
